#!/bin/bash
#SBATCH --job-name="clone git directories"
#SBATCH --partition="norm"
#SBATCH --time=24:00:00

git clone https://github.com/tdhock/PeakError.git
git clone https://github.com/tdhock/PeakSegJoint.git
git clone https://github.com/tdhock/PeakSegPipeline.git
git clone https://github.com/tdhock/PeakSegFPOP.git
