#!/bin/bash
#SBATCH --job-name="compute target tsv files"
#SBATCH --partition="norm"
#SBATCH --time=24:00:00

for lbed in dm6/samples/*/*/problems/*/labels.bed;do bash $(echo $lbed|sed 's/labels.bed/target.tsv.sh/');done
