__default__:
  prefix: "--time=1:00:00 --mem=4g --partition=norm"
bowtie2_index:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
bowtie2_map:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
bedtools:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
mark_duplicates:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
macs2:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
spp:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
samtools_sort:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
samtools_index:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
bedtools:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
bamcoverage:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
bigwigcompare:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
matrix_plot1:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
matrix_plot2:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
post_bedtools:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
chipqc1:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
chipqc2:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
spp2:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
fastqc:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
intervalstats1:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
intervalstats2:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
gat:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
fisher:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
jaccard:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
lineplots_by_sample:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
lineplots_by_kind:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
regex:
  prefix: "--time=1:00:00 --mem=4g --partition=norm"
macs2_v2:
  prefix: "--time=1:00:00 --mem=4g --partition=norm"
peakerror_compute:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
peakerror_summary:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
peakerror_visualize:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
peakerror_analyze:
  prefix: "--time=1:00:00 --mem=16g --partition=norm"
